baseURL = 'https://mufg80.github.io/'
languageCode = 'en-us'
title = ""
[params]
author = "Shannon Musgrave"
featured_image = "/images/rainbow.jpg"
favicon = ""
site_logo = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
cover_dimming_class = "bg-black-20"
body_classes = "times bg-washed-blue"
post_content_classes = "times"
text_color = "bg-washed-blue"
omit_header_text = false

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
