baseURL = 'https://mufg80.github.io/'
languageCode = 'en-us'
title = ""
theme = 'ananke'
[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-white"
cover_dimming_class = "bg-black-20"
featured_image_class = "cover bg-top"