baseURL = 'https://mufg80.github.io/'
languageCode = 'en-us'
title = ""
theme = 'ananke'
[params]
baseURL = 'https://mufg80.github.io/'
text_color = ""
author = "Shannon Musgrave"
featured_image = "/images/rainbow.jpg"
favicon = ""
site_logo = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
cover_dimming_class = "bg-black-20"
body_classes = "avenir bg-near-white"
